### ISSUE TITLE
Anlegen eines Events funktioniert nicht

### ISSUE THREAD

**Issue by bmjbaier** [CyriloMark/kostrjanc-v4#2]
Ich versuche ein Event anzulegen, was mir nicht nicht gelungen ist. Folgende Beobachtungen habe ich dabei gemacht:

1.
Anfangs erscheint für das Datum die Anzeige 1.1.1970 1:00 - 1.1.1970
Stattdessen würde ich vorschlagen, hier anzuzeigen: _(Datum/Uhrzeit noch nicht angegeben)_

2.
Festlegung des Orts des Events
Es ist für mich nicht  intuitiv klar, wie der Ort eines Events festgelegt werden kann. Das Stecknadelsymbol wandert bei jeder Wisch- und Zoombewegung mit. 
Vorschlag: Langer Touch oder Doppel-Touch setzt den Event-Ort. Ggfs. hierzu kurzen Hilfetext anzeigen.

3. 
Festlegung des Zeitpunkts des Events
Gibt es ein Date-Picker-Widget, dass man hier verwenden könnte?

4.
Weiter-Pfeil-Button
Klick auf den Button (Pfeil nach rechts) zeigt keine Reaktion. Möglicherweise habe ich nicht alle Angaben vollständig angegeben.
Falls das die Ursache ist, dass der Weiter-Pfeil nicht funktioniert, sollte eine Dialogbox angezeigt werden, welche die unvollständigen Informationen auflistet.
![Screenshot_20230402-114341](https://user-images.githubusercontent.com/27229372/229345230-5b768f86-ad97-41d8-afe3-33ab9eea69aa.png)

**Comment by Korla-tech** [comment]
wurde in neuster version behoben
