### ISSUE TITLE
Datum eines Posts soll angezeigt werden

### ISSUE THREAD

**Issue by bmjbaier** [CyriloMark/kostrjanc-v4#25]
Derzeit wird das Datum, wann ein neuer Beitrag erstellt oder gesendet wurde, nicht angezeigt. Ich finde es ungewöhnlich, dass diese "elementare" Information derzeit nicht angezeigt wird. Das Datum könnte z. B. bei der Titelzeile des Posts angezeigt werden.

**Comment by CyriloMark** [comment]
In der neuen Version gefixt. Datum befindet sich unterhalb des Beschreibungtextes.

**Comment by bmjbaier** [comment]
Das Issue ist  zwar schon geschlossen, trotzdem hier meine Beobachtungen:
- Es wird nicht Datum / Uhrzeit angezeigt des Posts, sondern wie alt der Post ist. Ich persönlich würde ersteres bevorzugen. Oder man macht es konfigurierbar, welche Darstellung bevorzugt wird.
- Das Alter des Posts wird nicht in der Übersicht angezeigt. Ich denke, so eine elementare Information gehört durchaus in die Übersicht (ggfs. konfigurierbar machen)
- Ja, ich weiß, ich gehöre schon zum älteren Eisen, aber ohne Brille bzw. Lupe ist die Information zum Alter des Posts für mich kaum entzifferbar (sehr kleine dunkelblaue Schrift auf schwarzem Hintergrund) Hier würde ich mir eine bessere Lesbarkeit wünschen.
