### ISSUE TITLE
Anzeige Statistiken und Informationen unter Kontoinformationen

### ISSUE THREAD

**Issue by bmjbaier** [CyriloMark/kostrjanc-v4#3]
Generell:
- Die angezeigten Informationen können scheinbar nicht einfach in die Zwischenablage kopiert werden,
Derzeit wird hier u. a. angezeigt:
- Expo Push Token: Wozu wird das benötigt?
- Link zum Profilbild mit URL zu Firebase: Wozu wird diese Information benötigt? Vorschlag: Weglassen

**Comment by Korla-tech** [comment]
hierbei handelt es sich nur um eine Fuktion die für aus Dateschutz Gründen existieren muss. Diese muss lediglich die Daten auflisten.
